apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    field.cattle.io/creatorId: user-844ll
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":443,"protocol":"HTTPS","serviceName":"gitlab:gitlab","ingressName":"gitlab:gitlab","hostname":"gitlab.hyx123.cn","allNodes":false}]'
  creationTimestamp: "2019-03-09T11:00:24Z"
  generation: 17
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-gitlab-gitlab
  name: gitlab
  namespace: gitlab
  resourceVersion: "669576"
  selfLink: /apis/apps/v1beta2/namespaces/gitlab/deployments/gitlab
  uid: 8a2098ff-425a-11e9-a634-00163e02623f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-gitlab-gitlab
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-03-09T15:37:12Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"gitlab","kind":"ClusterIP","name":"80tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-gitlab-gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ce:latest
        imagePullPolicy: Always
        name: gitlab
        ports:
        - containerPort: 80
          name: 80tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /etc/gitlab
          name: config
        - mountPath: /var/log/gitlab
          name: logs
        - mountPath: /var/opt/gitlab
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /srv/gitlab/config
          type: DirectoryOrCreate
        name: config
      - hostPath:
          path: /srv/gitlab/logs
          type: DirectoryOrCreate
        name: logs
      - hostPath:
          path: /srv/gitlab/data
          type: DirectoryOrCreate
        name: data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-03-09T11:00:24Z"
    lastUpdateTime: "2019-03-09T15:37:26Z"
    message: ReplicaSet "gitlab-7cf7795899" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-03-09T15:54:12Z"
    lastUpdateTime: "2019-03-09T15:54:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 17
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
